ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-y += -Iinclude/soc/oppo
ccflags-y += -Idrivers/input/oppo_face_drivers/include
ccflags-y += -DOPPO_MX6300_TEE_SUPPORT
obj-$(CONFIG_SPECTRA_CAMERA) += mx6300-spi.o

