obj-$(CONFIG_OPPO_DEVICE_INFO)	+=  oppo_devinfo/device_info.o
obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/oppo_project.o
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)	+=  project_info/boot_mode.o
obj-$(CONFIG_OPLUS_FEATURE_RECORD_MDMRST)	+=  oppo_mdmrst/oppo_mdmrst.o
obj-y += oplus_dummy_nodes.o
