# OPLUS internal build injects OPLUS_FEATURE_* globally; replicate for this subtree
ccflags-y += -DOPLUS_FEATURE_CHG_BASIC

# VOOC fast-charge MCU drivers (Find X DTS: oplus,stm8s-fastcg@26 / oplus,pic16f-fastcg@25)
obj-y   += oplus_stm8s.o
obj-y   += oplus_pic16f.o
obj-y   += oplus_n76e.o
obj-y   += oplus_vooc_fw.o
obj-y   += oplus_rk826.o
obj-y   += oplus_op10.o
